version: '3.3'

networks:
  servicebus:

services:

  test:
    image: node
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    user: root
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    networks:
      - servicebus
    command: npm run test

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - servicebus
    ports:
      - 5672:5672

  redis:
    image: redis
    networks:
      - servicebus
    ports:
      - 6379:6379
